export enum TipoIncidencia {
  PAQUETE_DANADO = 'PAQUETE_DANADO',
  DIRECCION_INCORRECTA = 'DIRECCION_INCORRECTA',
  CLIENTE_NO_ENCONTRADO = 'CLIENTE_NO_ENCONTRADO',
  VEHICULO_AVERIADO = 'VEHICULO_AVERIADO',
  RETRASO_TRAFICO = 'RETRASO_TRAFICO',
  OTRO = 'OTRO'
}